### PR TITLE
Program and Kit branch selections are deleteable

### LINKED ISSUE #604: Allow administrators to delete program schedule branch selections
In program scheduling, staff sometimes select the wrong program. Administrators can change scheduled times but cannot delete the branch selection outright (PsBranchSelections record).

### PR DESCRIPTION
**Pull request by madison-boman**
- Fix #604 Allow administrators to delete program schedule branch selections

### CODE REVIEW

**Comment by iafb** [comment]
- 📇 Includes database changes

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 1]
```diff
@@ -241,6 +243,33 @@ public async Task<IActionResult> PerformerDelete(PerformerListViewModel model)
...
+                var branch = await _siteService.GetBranchByIdAsync(branchSelection.BranchId);
+                var program = await _performerSchedulingService.GetProgramByIdAsync(branchSelection.ProgramId.Value);
+                branchSelection.IsDeleted = true;
+                await _performerSchedulingService.DeleteBranchSelectionAsync(branchSelection);
+                ShowAlertSuccess($"{branch.Name}'s selection of \"{program.Title}\" is deleted!.");
+            }
+            catch (GraException gex)
+            {
+                ShowAlertDanger("Unable to delete selection: ", gex);
+                return RedirectToAction(nameof(PerformerManagementController.PerformerSelections), new { id = model.Performer.Id });
```
Comment (haraldnagel) [inline src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Seems like we don't need this line as when it falls out it will do exactly this below.

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 2]
```diff
@@ -1523,6 +1552,33 @@ public async Task<IActionResult> KitDetails(KitDetailsViewModel model)
...
+                var branch = await _siteService.GetBranchByIdAsync(branchSelection.BranchId);
+                var kit = await _performerSchedulingService.GetKitByIdAsync(model.Kit.Id);
+                branchSelection.IsDeleted = true;
+                await _performerSchedulingService.DeleteBranchSelectionAsync(branchSelection);
+                ShowAlertSuccess($"{branch.Name}'s selection of \"{kit.Name}\" is deleted!");
+            }
+            catch (GraException gex)
+            {
+                ShowAlertDanger("Unable to delete selection: ", gex);
+                return RedirectToAction(nameof(PerformerManagementController.KitSelections), new { id = model.Kit.Id });
```
Comment (haraldnagel) [inline src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Again, shouldn't be needed since it does this on line 1579.

File: src/GRA.Data/Repository/PsBranchSelectionRepository.cs [hunk 3]
```diff
@@ -49,7 +49,9 @@ public async Task<int> GetCountByPerformerIdAsync(int performerId)
         {
             return await DbSet
                 .AsNoTracking()
-                .Where(_ => _.ProgramId.HasValue && _.Program.PerformerId == performerId)
+                .Where(_ => _.ProgramId.HasValue
```
Comment (haraldnagel) [inline src/GRA.Data/Repository/PsBranchSelectionRepository.cs]: Move the Where clause into the `.CountAsync()`

File: src/GRA.Data/Repository/PsBranchSelectionRepository.cs [hunk 4]
```diff
@@ -32,15 +32,15 @@ public async Task<int> GetCountByKitIdAsync(int kitId)
         {
             return await DbSet
                 .AsNoTracking()
-                .Where(_ => _.KitId.HasValue && _.KitId == kitId)
+                .Where(_ => _.KitId.HasValue && _.KitId == kitId && !_.IsDeleted)
```
Comment (haraldnagel) [inline src/GRA.Data/Repository/PsBranchSelectionRepository.cs]: Move the Where clause into the `CountAsync()`

File: src/GRA.Data/Repository/PsBranchSelectionRepository.cs [hunk 5]
```diff
@@ -85,7 +89,8 @@ public async Task<PsBranchSelection> GetByCodeAsync(string secretCode)
         {
             var selection = DbSet
                 .AsNoTracking()
-                .Where(_ => _.AgeGroupId == ageGroupId && _.BranchId == branchId);
+                .Where(_ => _.AgeGroupId == ageGroupId && _.BranchId == branchId
```
Comment (haraldnagel) [inline src/GRA.Data/Repository/PsBranchSelectionRepository.cs]: If we are going to break on an `&&` we should break on each `&&`

File: src/GRA.Domain.Service/PerformerSchedulingService.cs [hunk 6]
```diff
@@ -1451,6 +1451,7 @@ private async Task RemoveKitImageAsync(PsKitImage image)
                 branchSelection.BackToBackProgram);
 
             branchSelection.KitId = null;
+            branchSelection.IsDeleted = false;
```
Comment (haraldnagel) [inline src/GRA.Domain.Service/PerformerSchedulingService.cs]: Probably not necessary, bools are false by default.

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 7]
```diff
@@ -241,6 +243,33 @@ public async Task<IActionResult> PerformerDelete(PerformerListViewModel model)
...
         }
 
+        [HttpPost]
+        public async Task<IActionResult> PerformerSelectionDelete(PerformerSelectionsViewModel model)
+        {
+            var settings = await _performerSchedulingService.GetSettingsAsync();
+            var schedulingStage = _performerSchedulingService.GetSchedulingStage(settings);
+            if (schedulingStage < PsSchedulingStage.SchedulingOpen)
+            {
+                return RedirectToAction(nameof(PerformerManagementController.PerformerSelections), new { id = model.Performer.Id });
```
[the remark this answers is not in the document]
Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 7ea0e75f2f09c9275a89a5a37a81ef42cf2b2fba

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 8]
```diff
@@ -241,6 +243,33 @@ public async Task<IActionResult> PerformerDelete(PerformerListViewModel model)
...
+            }
+
+            try
+            {
+                var branchSelection = await _performerSchedulingService.GetBranchProgramSelectionByIdAsync(model.BranchSelectionId);
+                var branch = await _siteService.GetBranchByIdAsync(branchSelection.BranchId);
+                var program = await _performerSchedulingService.GetProgramByIdAsync(branchSelection.ProgramId.Value);
```
[the remark this answers is not in the document]
Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 5044ff45f01c4c5f7629dd13bae6f7f7b8c74a0a

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 9]
```diff
@@ -241,6 +243,33 @@ public async Task<IActionResult> PerformerDelete(PerformerListViewModel model)
...
+                branchSelection.IsDeleted = true;
+                await _performerSchedulingService.DeleteBranchSelectionAsync(branchSelection);
+                ShowAlertSuccess($"{branch.Name}'s selection of \"{program.Title}\" is deleted!.");
+            }
+            catch (GraException gex)
+            {
+                ShowAlertDanger("Unable to delete selection: ", gex);
```
[the remark this answers is not in the document]
Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 5044ff45f01c4c5f7629dd13bae6f7f7b8c74a0a

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 10]
```diff
@@ -1523,6 +1552,33 @@ public async Task<IActionResult> KitDetails(KitDetailsViewModel model)
...
+            if (schedulingStage == PsSchedulingStage.Unavailable)
+            {
+                return RedirectToAction(nameof(PerformerManagementController.KitSelections), new { id = model.Kit.Id });
+            }
+
+            try
+            {
+                var branchSelection = await _performerSchedulingService.GetBranchProgramSelectionByIdAsync(model.BranchSelectionId);
+                var branch = await _siteService.GetBranchByIdAsync(branchSelection.BranchId);
+                var kit = await _performerSchedulingService.GetKitByIdAsync(model.Kit.Id);
```
[the remark this answers is not in the document]
Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 5044ff45f01c4c5f7629dd13bae6f7f7b8c74a0a

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 11]
```diff
@@ -1523,6 +1552,33 @@ public async Task<IActionResult> KitDetails(KitDetailsViewModel model)
...
+                branchSelection.IsDeleted = true;
+                await _performerSchedulingService.DeleteBranchSelectionAsync(branchSelection);
+                ShowAlertSuccess($"{branch.Name}'s selection of \"{kit.Name}\" is deleted!");
+            }
+            catch (GraException gex)
+            {
+                ShowAlertDanger("Unable to delete selection: ", gex);
```
[the remark this answers is not in the document]
Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 5044ff45f01c4c5f7629dd13bae6f7f7b8c74a0a

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs (hunk 1 above)
Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 5044ff45f01c4c5f7629dd13bae6f7f7b8c74a0a

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs (hunk 2 above)
Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 5044ff45f01c4c5f7629dd13bae6f7f7b8c74a0a

File: src/GRA.Data/Repository/PsBranchSelectionRepository.cs (hunk 3 above)
Comment (madison-boman) [reply src/GRA.Data/Repository/PsBranchSelectionRepository.cs]: Fixed in 7ea0e75f2f09c9275a89a5a37a81ef42cf2b2fba

File: src/GRA.Data/Repository/PsBranchSelectionRepository.cs (hunk 4 above)
Comment (madison-boman) [reply src/GRA.Data/Repository/PsBranchSelectionRepository.cs]: 7ea0e75f2f09c9275a89a5a37a81ef42cf2b2fba

File: src/GRA.Data/Repository/PsBranchSelectionRepository.cs (hunk 5 above)
Comment (madison-boman) [reply src/GRA.Data/Repository/PsBranchSelectionRepository.cs]: Fixed in 7ea0e75f2f09c9275a89a5a37a81ef42cf2b2fba

File: src/GRA.Domain.Service/PerformerSchedulingService.cs (hunk 6 above)
Comment (madison-boman) [reply src/GRA.Domain.Service/PerformerSchedulingService.cs]: Fixed in 7ea0e75f2f09c9275a89a5a37a81ef42cf2b2fba

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 12]
```diff
@@ -241,6 +243,38 @@ public async Task<IActionResult> PerformerDelete(PerformerListViewModel model)
...
+            }
+            try
+            {
+                var branchSelection = await _performerSchedulingService
+                    .GetBranchProgramSelectionByIdAsync(model.BranchSelectionId);
+                await _performerSchedulingService.DeleteBranchSelectionAsync(branchSelection);
+                var branch = await _siteService.GetBranchByIdAsync(branchSelection.BranchId);
+                var program = await _performerSchedulingService
+                    .GetProgramByIdAsync(branchSelection.ProgramId.Value);
+                branchSelection.IsDeleted = true;
```
Comment (iafb) [inline src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Can be removed, IsDeleted is set in DeleteBranchSelectionAsync()

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 13]
```diff
@@ -241,6 +243,38 @@ public async Task<IActionResult> PerformerDelete(PerformerListViewModel model)
...
+                ShowAlertSuccess($"{branch.Name}'s selection of \"{program.Title}\" is deleted!.");
+            }
+            catch (GraException gex)
+            {
+                ShowAlertDanger("Unable to delete selection: ", gex);
+                _logger.LogError("Error deleting branch selection Id" +
+                    $"{model.BranchSelectionId} by user {GetId(ClaimType.UserId)}: {gex}", gex);
```
Comment (iafb) [inline src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: LogError should use arguments to set the variables instead of string interpolation
Example: 

    _logger.LogError(gex,
        "Problem displaying index for user {GetActiveUserId}: {Message}",
        GetActiveUserId(),
        gex.Message);

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs [hunk 14]
```diff
@@ -1523,6 +1557,35 @@ public async Task<IActionResult> KitDetails(KitDetailsViewModel model)
...
+                await _performerSchedulingService.DeleteBranchSelectionAsync(branchSelection);
+                var branch = await _siteService.GetBranchByIdAsync(branchSelection.BranchId);
+                var kit = await _performerSchedulingService.GetKitByIdAsync(model.Kit.Id);
+                ShowAlertSuccess($"{branch.Name}'s selection of \"{kit.Name}\" is deleted!");
+            }
+            catch (GraException gex)
+            {
+                ShowAlertDanger("Unable to delete selection: ", gex);
+                _logger.LogError("Error deleting branch selection Id" +
+                    $"{model.BranchSelectionId} by user {GetId(ClaimType.UserId)}: {gex}", gex);
```
Comment (iafb) [inline src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: LogError should use arguments to set the variables instead of string interpolation
Example: 

    _logger.LogError(gex,
        "Problem displaying index for user {GetActiveUserId}: {Message}",
        GetActiveUserId(),
        gex.Message);

Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 9bf3f38be7dda584a234205340b36076a97d5cc0

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs (hunk 13 above)
Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 9bf3f38be7dda584a234205340b36076a97d5cc0

File: src/GRA.Controllers/MissionControl/PerformerManagementController.cs (hunk 12 above)
Comment (madison-boman) [reply src/GRA.Controllers/MissionControl/PerformerManagementController.cs]: Fixed in 9bf3f38be7dda584a234205340b36076a97d5cc0
